apiVersion: v1
kind: Pod
metadata:
  name: malaas
  labels:
    app: malaas
    name: malaas-pod
spec:
  containers:
    - name: exploiter-core
      image: exploiter-core:0.1.0
      env:
        - name: KAFKA_BOOTSTRAP_SERVER
          value: <kafka-server-port>
    - name: exploiter-data-collector
      image: exploiter-data-collector:0.1.0
      env:
        - name: KAFKA_BOOTSTRAP_SERVER
          value: <kafka-server-port>
