apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-deployment
  labels:
    app: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: spotify/kafka
        ports:
        - name: kafka_port
          containerPort: 9092
          targetPort: 9092
        - name: zk_port
          containerPort: 2181
          targetPort: 2181
